### ISSUE TITLE
[Feature] WildMatch

### ISSUE THREAD

**Issue by RF-Tar-Railt** [ArcletProject/Alconna#3]
泛匹配(可以的话

**Comment by GreyElaina** [comment]
规定提议: 在一个匹配规则中 WildMatch 允许且应只允许出现一次, 且出现在匹配模式最后.

**Comment by RF-Tar-Railt** [comment]
> 规定提议: 在一个匹配规则中 WildMatch 允许且应只允许出现一次, 且出现在匹配模式最后.
限制解除

**Comment by RF-Tar-Railt** [comment]
0.4.1
