### ISSUE TITLE
[Feature] 明确测试脚本

### ISSUE THREAD

**Issue by wyapx** [ArcletProject/Alconna#36]
### 检查

* [x] 新特性的目的明确
* [x] 我已经阅读了文档 [the wiki](https://arcletproject.github.io/docs/alconna/tutorial) 并且找不到类似特性

# Feature
### 概要

在项目中添加`benchmark.py`以供参考

### 其他内容

在 [文档](https://arcletproject.github.io/docs/alconna/tutorial/#%E6%80%A7%E8%83%BD%E5%8F%82%E8%80%83) 中没有指出使用哪个脚本进行性能测试，希望可以在仓库中添加一个`benchmark.py`作为参考

**Comment by RF-Tar-Railt** [comment]
加在readme里了
