### ISSUE TITLE
[Bug] Alconna对象不可转换到字符串导致 nonebot-plugin-alchelper 中的全局HelperExtension不可用

### ISSUE THREAD

**Issue by DynamicLoader** [ArcletProject/Alconna#93]
## 请确认：

* [x] 问题的标题明确
* [x] 我翻阅过其他的issue并且找不到类似的问题
* [x] 我已经阅读了文档 [the wiki](https://arcletproject.github.io/docs/alconna/tutorial) 并仍然认为这是一个Bug

# Bug

如题，在[这里](https://github.com/RF-Tar-Railt/nonebot-plugin-alchelper/issues/1)有相似的报告，和我本地运行的结果是一致的。

## 问题

阅读代码发现这里的 res.source 类型是`Alconna`，且没有到`str`的默认转换方法：
https://github.com/RF-Tar-Railt/nonebot-plugin-alchelper/blob/448e9db72e581678da9bf20511b7bf67403ad8f8/src/nonebot_plugin_alchelper/__init__.py#L100

这导致持久化到数据库时发生类型不匹配的异常，而且由于这是全局注册的wrapper，所有使用了Alconna的命令/插件都受影响。

## 如何复现

安装nonebot-plugin-alchelper插件并连接到napcat，发送/help即可触发

## 预期行为

提供一个`__str__`方法，指明命令所属的命名空间::原始匹配。

## 使用环境:
- Python 版本: 3.12.8
- Alconna 版本: 0.54.1

## 日志/截图

![{0BE0BDBE-5614-4546-8C8E-EBD748DD70CA}](https://github.com/user-attachments/assets/2956517b-b51a-4e1c-880f-1756ec523b4d)

暂时修复性的更改，破坏记录功能：
![{42007919-5369-4AFF-A5B4-7F7A38355D20}](https://github.com/user-attachments/assets/d7fac500-d16f-4935-9df2-d0245ef57b64)

**Comment by RF-Tar-Railt** [comment]
这个应该算alchelper插件的问题，而不是Alconna本体的
另外如果仅需要 `help` 现在更推荐去用 `nonebot_plugin_alconna` 的内置 help 插件

**Comment by RF-Tar-Railt** [comment]
> 这个应该算alchelper插件的问题，而不是Alconna本体的 另外如果仅需要 `help` 现在更推荐去用 `nonebot_plugin_alconna` 的内置 help 插件

如果仍然坚持开 issue 的话，去alchelper下面发

**Comment by DynamicLoader** [comment]
感谢回复！不在roadmap上就不动了，不过仍然建议您给alchelper标一下这个已知问题，谢谢！
